"""Writes <lang>.lproj/Localizable.strings + InfoPlist.strings for the Mac HUD.
Source of truth: keys.json (English, the development language) + translations.json."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HERE = ROOT / "Localization"
keys = json.loads((HERE / "keys.json").read_text())
tr = json.loads((HERE / "translations.json").read_text()) if (HERE / "translations.json").exists() else {}

PLIST_EN = {
    "mac.NSMicrophoneUsageDescription": "voice-loop listens to your reply to the agent when you click a chat in the panel. Audio is transcribed locally and never leaves your Mac.",
}
LANGS = ["en"] + sorted(tr)

def q(s):
    # Keys/values keep their \n escape sequences; only unescaped double quotes need escaping.
    return '"' + s.replace('"', '\\"') + '"'

def write(dest, lang):
    table = {k: k for k in keys} if lang == "en" else tr[lang]
    plist = PLIST_EN if lang == "en" else tr[lang]
    for app, folder in (("mac", ROOT / "HUD/Resources"),):
        d = folder / f"{lang}.lproj"
        d.mkdir(parents=True, exist_ok=True)
        (d / "Localizable.strings").write_text(
            "/* Generated by Localization/generate.py — edit translations.json instead. */\n"
            + "".join(f"{q(k)} = {q(table.get(k, k))};\n" for k in keys))
        (d / "InfoPlist.strings").write_text("".join(
            f'{name.split(".", 1)[1]} = {q(plist[name])};\n' for name in PLIST_EN if name.startswith(app + ".")))

for lang in LANGS:
    write(ROOT, lang)
(HERE / "languages.txt").write_text("\n".join(LANGS) + "\n")
print("languages:", ", ".join(LANGS))
