#!/bin/zsh
# Builds VoiceLoopHUD.app (menu-bar only, no Dock icon) next to this script.
set -e
cd "$(dirname "$0")"
swift build -c release
APP=VoiceLoopHUD.app
rm -rf $APP
mkdir -p $APP/Contents/MacOS $APP/Contents/Resources
cp .build/release/VoiceLoopHUD $APP/Contents/MacOS/
cp ../Branding/AppIcon.icns $APP/Contents/Resources/
cp -R Resources/*.lproj $APP/Contents/Resources/   # generated by Localization/generate.py
cat > $APP/Contents/Info.plist <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>CFBundleIdentifier</key><string>me.volostnov.voiceloop.hud</string>
  <key>CFBundleName</key><string>VoiceLoopHUD</string>
  <key>CFBundleExecutable</key><string>VoiceLoopHUD</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleIconFile</key><string>AppIcon</string>
  <key>CFBundleDevelopmentRegion</key><string>en</string>
  <key>CFBundleAllowMixedLocalizations</key><true/>
  <key>CFBundleDisplayName</key><string>voice-loop</string>
  <key>CFBundleShortVersionString</key><string>0.1</string>
  <key>LSMinimumSystemVersion</key><string>15.0</string>
  <key>LSUIElement</key><true/>
  <key>NSLocalNetworkUsageDescription</key><string>voice-loop shows its panel on your iPhone over your home network. Data is encrypted and never goes to the internet.</string>
  <key>NSBonjourServices</key><array><string>_voiceloop._tcp</string></array>
  <key>NSMicrophoneUsageDescription</key><string>voice-loop listens to your reply to the agent when you click a chat in the panel. Audio is transcribed locally and never leaves your Mac.</string>
</dict></plist>
PLIST
codesign --force --sign - $APP
# Install into ~/Applications so it can be found in Spotlight / Launchpad.
mkdir -p ~/Applications
rm -rf ~/Applications/$APP
cp -R $APP ~/Applications/
echo "built $PWD/$APP → ~/Applications/$APP"
